### ISSUE TITLE
StrictMode policy violation: android.os.strictmode.DiskReadViolation

### ISSUE THREAD

**Issue by rohitjakhar** [ChuckerTeam/chucker#1129]
## :writing_hand: Describe the bug

While I am using StrctMode for testing app i found this issue in Chucker.

```
StrictMode policy violation; ~duration=839 ms: android.os.strictmode.DiskWriteViolation
at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1629)
at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:365)
at libcore.io.ForwardingOs.remove(ForwardingOs.java:673)
at android.app.ActivityThread$AndroidOs.remove(ActivityThread.java:8002)
at java.io.UnixFileSystem.delete(UnixFileSystem.java:363)
at java.io.File.delete(File.java:1035)
at com.chuckerteam.chucker.internal.data.room.ChuckerDatabase$Companion.create(ChuckerDatabase.kt:22)
at com.chuckerteam.chucker.internal.data.repository.RepositoryProvider.initialize(RepositoryProvider.kt:34)
at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:32)
at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:23)
at com.chuckerteam.chucker.api.ChuckerInterceptor$Builder.build(ChuckerInterceptor.kt:366)                                                                                              
```

**Comment by leinardi** [comment]
I have StrictMode enabled but I don't get this violation (API 29), on which API level do you get it?
