### ISSUE TITLE
Share Crash TransactionTooLargeException

### ISSUE THREAD

**Issue by eneskarpuzoglu** [ChuckerTeam/chucker#1160]
## :writing_hand: Describe the bug
Crashes when trying to share a request with a large response

## :bomb: Steps to reproduce
1. Go to Chucker
2. tap on big responsed request detail
3. tap share icon and tap 'share as text'
5. Crash occured

## :iphone: Tech info
- Emulator or other devices has same crash
Brand:Google
Model:Sdk_gphone64_arm64
Orientation:Portrait
RAM free: 391.43 MB
Disk free: 1.96 GB
Version:Android 13
Orientation:Portrait
Rooted:No
 - Chucker version: 4.0.0 and earlier

## :page_facing_up: Additional context
Fatal Exception: java.lang.RuntimeException: Failure from system
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1841)
       at android.app.Activity.startActivityForResult(Activity.java:5471)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:754)
       at android.app.Activity.startActivityForResult(Activity.java:5429)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:735)
       at android.app.Activity.startActivity(Activity.java:5927)
       at android.app.Activity.startActivity(Activity.java:5894)
       at com.chuckerteam.chucker.internal.ui.transaction.TransactionActivity$shareTransactionAsText$1.invokeSuspend(TransactionActivity.kt:117)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Caused by android.os.TransactionTooLargeException: data parcel size 1048948 bytes
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:584)
       at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2053)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1834)
       at android.app.Activity.startActivityForResult(Activity.java:5471)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:754)
       at android.app.Activity.startActivityForResult(Activity.java:5429)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:735)
       at android.app.Activity.startActivity(Activity.java:5927)
       at android.app.Activity.startActivity(Activity.java:5894)
       at com.chuckerteam.chucker.internal.ui.transaction.TransactionActivity$shareTransactionAsText$1.invokeSuspend(TransactionActivity.kt:117)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7872)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by mongkon-ttb** [comment]
Have you solved this issue ? My app also crashed with the same log (TransactionTooLargeException)

Chucker version : 3.5.2

**Comment by eneskarpuzoglu** [comment]
Yes issue continuing

**Comment by Khudoyshukur** [comment]
```
private fun shareTransactionAsText(block: (HttpTransaction) -> Sharable): Boolean {
        val transaction = viewModel.transaction.value
        if (transaction == null) {
            showToast(getString(R.string.chucker_request_not_ready))
            return true
        }
        val sharable = block(transaction)
        lifecycleScope.launch {
            val shareIntent =
                sharable.shareAsUtf8Text(
                    activity = this@TransactionActivity,
                    intentTitle = getString(R.string.chucker_share_transaction_title),
                    intentSubject = getString(R.string.chucker_share_transaction_subject),
                )
            startActivity(shareIntent)
        }
        return true
    }
```

@cortinico I think we can't do anything here, the issue is happening because the user is trying to send large text via intent, thus getting exception: `android.os.TransactionTooLargeException: data parcel size 1048948 bytes`

The only thing that is helpful would be that we can catch such exception and show the user proper message that `Share as text` is not available for this endpoint and recommend them to use `Share as file`.

What do you say on this? Can I work on that warning dialog? @cortinico

**Comment by cortinico** [comment]
> we can catch such exception and show the user proper message that `Share as text` is not available for this endpoint and recommend them to use `Share as file`.

Yeah potentially we don't show the "Share as text" option at all if the payload is too long
