### ISSUE TITLE
Crash when chucker is used with proguard enabled.

### ISSUE THREAD

**Issue by prithvibhola** [ChuckerTeam/chucker#163]
Chucker is crashing with these crash logs when clicked on the notification. It is working fine in the debug build when proguard is not enabled but crashing when the proguard is enabled.

2019-11-26 17:39:06.222 18381-18381/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gojek.driver.bike.staging, PID: 18381
    android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at dark.Ɨſ.onCreateView(:65)
        at dark.ιʟ.performCreateView(:2439)
        at dark.Іɹ.ˊ(:1460)
        at dark.Іɹ.ॱॱ(:1784)
        at dark.Іɹ.ॱ(:1852)
        at dark.ϙ.ॱॱ(:802)
        at dark.Іɹ.ˋ(:2625)
        at dark.Іɹ.ˊ(:2411)
        at dark.Іɹ.ˋ(:2366)
        at dark.Іɹ.ˏ(:2243)
        at dark.ϙ.ʼ(:654)
        at dark.іɹ.finishUpdate(:146)
        at dark.ɨӏ.ˊ(:1244)
        at dark.ɨӏ.ˏ(:1092)
        at dark.ɨӏ.onMeasure(:1622)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at dark.ɩı.onMeasure(:143)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:717)
        at android.view.View.measure(View.java:23355)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2919)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1749)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2042)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1637)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7797)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
        at android.view.Choreographer.doCallbacks(Choreographer.java:984)
        at android.view.Choreographer.doFrame(Choreographer.java:809)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-11-26 17:39:06.222 18381-18381/? E/AndroidRuntime: Caused by: java.lang.IllegalStateException: Binary XML file line #17: Unable to find LayoutManager dark.LinearLayoutManager
        at dark.ιɍ.ˊ(:810)
        at dark.ιɍ.<init>(:713)
        at dark.ιɍ.<init>(:647)
        	... 65 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "dark.LinearLayoutManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.gojek.driver.bike.staging-QEokmeEQhz6U6wW5zueoIg==/base.apk"],nativeLibraryDirectories=[/data/app/com.gojek.driver.bike.staging-QEokmeEQhz6U6wW5zueoIg==/lib/arm64, /data/app/com.gojek.driver.bike.staging-QEokmeEQhz6U6wW5zueoIg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at dark.ιɍ.ˊ(:791)
        	... 67 more

**Comment by vbuberen** [comment]
Hey @prithvibhola 
Wanted to make sure that you used Chucker with ProGuard on purpose, not just in release production app.

As to the issue itself - interesting. I will try to reproduce it and in case of success might work on rules to include into the library.

**Comment by autonomousapps** [comment]
I had a similar issue with proguard:

> 12-12 13:24:24.910 16525-16525/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.myapp.star, PID: 16525
>     java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Lcom/chuckerteam/chucker/api/ChuckerCollector;JLjava/util/Set;ILkotlin/o/d/g;)V in class Lc/a/a/a/a; or its super classes (declaration of ‘c.a.a.a.a’ appears in /data/app/com.hiya.star-1/base.apk)”

Something to do with the overloaded constructor

**Comment by prithvibhola** [comment]
Hey @vbuberen,

The issue is coming because of setting the **LayoutManager**  in the XML. The files are obfuscated and LayoutManager is not set properly.

```
<androidx.recyclerview.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scrollbars="vertical"
    **app:layoutManager="LinearLayoutManager"**
    tools:context="com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment"
    tools:listitem="@layout/chucker_list_item_transaction" />

```

Quick Fix:
For now, I have included this rule in the proguard file

`-keep class androidx.recyclerview.widget.** { *; }`

Also, the issue can be fixed if LayoutManager is removed from the XML file and is set within the Java/Kotlin code.

**Comment by vbuberen** [comment]
@prithvibhola 
Thanks for getting back and providing details.
However, I have never seen such issue before on other projects I work on as a daily job. Both ProGuard and R8 always worked well and respected layout managers set from XML.

Anyway, I will take a look considering your info. Probably, some `consumer` rules might be included into a library package as other libs often have.

**Comment by prithvibhola** [comment]
@vbuberen 

From the crash logs 
Caused by: java.lang.ClassNotFoundException: Didn't find class "dark.LinearLayoutManager" on path

**-repackageclasses "dark"** might be the reason that I was getting this issue.  It repackages all class files and moves them into the single given package.

**Comment by vbuberen** [comment]
@prithvibhola 
Now it makes sense. Your `-repackageclasses "dark" breaks` the build, since `LinearLayoutManager` class is placed in `androidx.recyclerview.widget.LinearLayoutManager` package.

Also, note that on latest stable version of Chucker, which is `3.0.1` at the moment, there is no such issue, so feel free to rollback for a little bit till @cortinico gets back from his vacation and releases a new version.

As to your solution - I would still stick to LayoutManager being set in xml file rather than code.
And I have a solution which would work for your case. Will create a PR shortly.

**Comment by vbuberen** [comment]
@autonomousapps 
Hey there. It seems that issue is slightly different from the one originally report by the author of this issue. Would you mind creating a new issue with more details about your problem?
Like version of Chucker used, the error itself (as reported here) etc.
