### ISSUE TITLE
OutOfMemoryError in interceptor

### ISSUE THREAD

**Issue by Nekromancer** [ChuckerTeam/chucker#218]
## :loudspeaker: Describe the bug
This came to me from firebase crashlytics, i don't know the reproduction steps
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 13536178 byte allocation with 5074056 free bytes and 4MB until OOM
       at okio.Buffer.readByteArray(Buffer.java:1438)
       at okio.Buffer.readString(Buffer.java:301)
       at okio.Buffer.readString(Buffer.java:290)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.processResponseBody(ChuckerInterceptor.java:156)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.processResponse(ChuckerInterceptor.java:130)
       at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.java:61)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
// rest of interceptors
```

## :bomb: To Reproduce
I don't know how to reproduce that

### :wrench: Expected behavior
Chucker should handle any payload size gracefully

## :iphone: Smartphone
 - Device: Galaxy A5 (2016)
 - OS: 7.1.1
 - Lib version: 3.1.1

**Comment by vbuberen** [comment]
Hi @Nekromancer 
Any updates on this issue? Were you able to see it in Crashlytics again?

**Comment by Nekromancer** [comment]
Hi,

No, not a single occurence in 2 weeks

**Comment by vbuberen** [comment]
Got it, thanks. I am not closing it, just wanted a status update.

You have Chucker somewhere in production app? 
Or it is just Crashlytics for internal QA devices?

**Comment by Nekromancer** [comment]
I have chucker on staging version for internal and external (clients) QA. It does not go into production itself

**Comment by vbuberen** [comment]
I believe that this is the same problem as in #263
