### ISSUE TITLE
LeakedClosableViolation

### ISSUE THREAD

**Issue by Pitel** [ChuckerTeam/chucker#318]
## :writing_hand: Describe the bug
When strict mode is enabled, it complains some resource is not closed by Chucker

## :bomb: Steps to reproduce

1. Enable StricMode
    ```kotlin
    StrictMode.setThreadPolicy(
        StrictMode.ThreadPolicy.Builder()
            .detectAll()
            .penaltyLog()
            .build()
        )
    StrictMode.setVmPolicy(
        StrictMode.VmPolicy.Builder()
            .detectAll()
            .penaltyLog()
            .build()
        )
    ```
2. Use Chucker as usual, do some HTTP requests, watch Logcat.
3. Notice `StrictMode policy violation` in Logcat

## :wrench: Expected behavior

No `StrictMode policy violation`s.

## :camera: Screenshots

```
2020-04-07 09:26:34.245 21511-21534 D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.io.FileInputStream.finalize(FileInputStream.java:493)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.io.FileInputStream.<init>(FileInputStream.java:174)
        at okio.Okio.source(Okio.kt:184)
        at com.chuckerteam.chucker.api.ChuckerInterceptor$ChuckerTransactionTeeCallback.readResponseBuffer(ChuckerInterceptor.kt:251)
        at com.chuckerteam.chucker.api.ChuckerInterceptor$ChuckerTransactionTeeCallback.onSuccess(ChuckerInterceptor.kt:239)
        at com.chuckerteam.chucker.internal.support.TeeSource.close(TeeSource.kt:69)
        at okio.RealBufferedSource.close(RealBufferedSource.kt:498)
        at okhttp3.internal.Util.closeQuietly(Util.kt:488)
        at okhttp3.ResponseBody.close(ResponseBody.kt:192)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody.close(OkHttpCall.java:310)
        at retrofit2.BuiltInConverters$UnitResponseBodyConverter.convert(BuiltInConverters.java:74)
        at retrofit2.BuiltInConverters$UnitResponseBodyConverter.convert(BuiltInConverters.java:70)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 

```

## :iphone: Tech info
 - Device: Pixel 3a
 - OS: 10
 - Chucker version: 3.2.0

## :page_facing_up: Additional context

Chucker 3.1 was ok.

**Comment by vbuberen** [comment]
Thanks for reporting this issue. 
It was reported yesterday and already fixed by #316.
Feel free to switch to develop snapshot which has this fix along with some other minor UI fixes.
