### ISSUE TITLE
StrictModeViolation: GzipSource is not closed

### ISSUE THREAD

**Issue by mattprecious** [ChuckerTeam/chucker#472]
## :writing_hand: Describe the bug
```
Caused by: java.lang.Throwable: Explicit termination method 'end' not called
   at dalvik.system.CloseGuard.open(CloseGuard.java:237)
   at java.util.zip.Inflater.<init>(Inflater.java:122)
   at okio.GzipSource.<init>(GzipSource.kt:44)
   at com.chuckerteam.chucker.internal.support.IOUtils.getNativeSource(IOUtils.kt:59)
   at com.chuckerteam.chucker.api.ChuckerInterceptor.processRequest(ChuckerInterceptor.kt:132)
   at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:97)
```

## :bomb: Steps to reproduce
```
StrictMode.setVmPolicy(
  VmPolicy.Builder()
    .detectLeakedClosableObjects()
    .penaltyLog()
    .penaltyDeath()
)
```

Call an endpoint using gzip compression.

## :wrench: Expected behavior
No violation. `GzipSource` is closed.

## :iphone: Tech info
 - Chucker version: 3.3.0

**Comment by vbuberen** [comment]
Thanks for reporting.

While trying to reproduce found out that in our sample app we don't actually have a request with a proper header for Gzip, so have nothing going through `GzipSource` and this is why don't see the same issue.

**Comment by cortinico** [comment]
> While trying to reproduce

Have you had any luck reproducing this @vbuberen ?

**Comment by vbuberen** [comment]
Yes. To reproduce you can manually add `Content-Encoding` header with `gzip` value to a request in our sample app.
Only with this header `ChuckerInterceptor` will call the code which makes strict mode complain.
This is why I mentioned that we have no good request in the sample app at the moment.
