### ISSUE TITLE
Cannot access database on the main thread

### ISSUE THREAD

**Issue by BenazirSh** [ChuckerTeam/chucker#487]
Exception: java.lang.IllegalStateException
java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
 at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:267)
 at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:351)
 at com.chuckerteam.chucker.internal.data.room.HttpTransactionDao_Impl.update(HttpTransactionDao_Impl.java:345)
 at com.chuckerteam.chucker.internal.data.repository.HttpTransactionDatabaseRepository.updateTransaction(HttpTransactionDatabaseRepository.kt:37)
 at com.chuckerteam.chucker.api.ChuckerCollector.onResponseReceived$com_github_ChuckerTeam_Chucker_library(ChuckerCollector.kt:71)
 at com.chuckerteam.chucker.api.ChuckerInterceptor$ChuckerTransactionTeeCallback.onSuccess(ChuckerInterceptor.kt:242)
 at com.chuckerteam.chucker.internal.support.TeeSource.close(TeeSource.kt:69)
 at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
 at okio.ForwardingSource.close(ForwardingSource.kt:34)
 at okio.RealBufferedSource.close(RealBufferedSource.kt:477)
 at okio.RealBufferedSource$inputStream$1.close(RealBufferedSource.kt:170)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
 at android.os.Handler.handleCallback(Handler.java:914)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7560)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by BenazirSh** [comment]
I'm getting the error as above

**Comment by MiSikora** [comment]
Please update your issue with our bug report template.

From your stack trace it looks like you are closing the response on the main thread. You can fix it by processing/closing the response on a background thread and posting the result to the main thread.

As for the solution in the library it could be solved with a custom executor that processes results. I mentioned it in the next steps of #267. Although, to be perfectly honest, I'm not sure if we should change it just for this reason. Closing response on the main thread is not the best thing. It might require synchronisation and other work which can block the main thread even without `ChuckerInterceptor` - https://github.com/square/okhttp/blob/f1bc9d1d3339d0696e232a5d8a2d7830630a8242/okhttp/src/main/kotlin/okhttp3/internal/http2/Http2Stream.kt#L473-L487.

**Comment by adityat-sportsbet** [comment]
<img width="1262" alt="Screen Shot 2021-03-25 at 5 42 34 pm" src="https://user-images.githubusercontent.com/57159362/112442987-84f71080-8da0-11eb-879a-8a6652ce9ae9.png">

I am getting the same error, on the latest version 3.4.0.
Works fine when chucker is disabled.

**Comment by MiSikora** [comment]
How are you handling threads in your Rx chain?

**Comment by CompuGenius** [comment]
I am still getting this error. Is there a way to fix it? I'm using version 3.5.2

**Comment by CompuGenius** [comment]
I had the same issue, spent a long time trying to get this and other packages working, finally figured out that I need to use the sonatype snapshot version.
Maybe add that to the readme, or add it to the main release?

**Comment by MiSikora** [comment]
Readme isn't a place to track issues and changes. There is the changelog for that type of stuff. We do mention snapshot versions in the changelog, though.
