### ISSUE TITLE
Chucker crash opening responses

### ISSUE THREAD

**Issue by marta-larranaga** [ChuckerTeam/chucker#57]
**Describe the bug**
When opening Chucker in device and clicking to see the description of an Http Request, it crashes 

**To Reproduce**
1. Go to Chucker
2. Click on an HttpRequest
4. Appli crashes :  
 java.lang.IncompatibleClassChangeError: Class 'com.chuckerteam.chucker.api.internal.ui.transaction.TransactionActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/xxx.debug-re4vlTGo19DGjF2gM0nfUw==/split_lib_dependencies_apk.apk)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionActivity.onResume(TransactionActivity.java:88)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Smartphone**
 - Device: Nexus 5X
 - OS: Android 9
 - Lib version: 3.0.0-alpha1

**Comment by cortinico** [comment]
Hey @marta-larranaga 
Thanks for the bug report.

Apparently the problem is related to AndroidX. Please note that we haven't migrated yet to AndroidX, and looks like your project is migrated instead.

You need to make sure that you have the Jetifier enabled:
https://developer.android.com/studio/command-line/jetifier

Can you confirm that you have Jetifier enabled?

**Comment by KatieBarnett-Bilue** [comment]
I have jetifier enabled and I am seeing the same issue. Same stacktrace as well.

**Comment by cortinico** [comment]
@KatieBarnett-Bilue @marta-larranaga Do you have a Github repo to share that I can take a look.
I'm unfortunately unable to reproduce this issue.

**Comment by banasiak** [comment]
I'm also seeing this same stacktrace on v3.0.1 which has been migrated to AndroidX.

Device: Pixel 3XL
OS: Android Q Beta 6
Lib version: 3.0.1

**Comment by cortinico** [comment]
> I'm also seeing this same stacktrace on v3.0.1 which has been migrated to AndroidX.

Hey @banasiak 
Version v3.0.1 is not migrated to AndroidX. Version 3.1 will be, but it's not released yet.

**Comment by banasiak** [comment]
OK. Thanks for clarifying!
