### ISSUE TITLE
Protobuf request in sample throws exception

### ISSUE THREAD

**Issue by vbuberen** [ChuckerTeam/chucker#571]
## :writing_hand: Describe the bug
While updating #563 with latest changes from #569 saw the following exception in a stacktrace:
```I/Chucker: Decoding with: com.chuckerteam.chucker.sample.PokemonProtoBodyDecoder@3e40612
W/Chucker: Decoder com.chuckerteam.chucker.sample.PokemonProtoBodyDecoder@3e40612 failed to process request payload
    java.net.ProtocolException: Unexpected end group
        at com.squareup.wire.ProtoReader.nextTag(ProtoReader.kt:152)
        at com.chuckerteam.chucker.sample.Pokemon$Companion$ADAPTER$1.decode(Pokemon.kt:131)
        at com.chuckerteam.chucker.sample.Pokemon$Companion$ADAPTER$1.decode(Pokemon.kt:83)
        at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:321)
        at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:320)
        at com.chuckerteam.chucker.sample.PokemonProtoBodyDecoder.decodeRequest(PokemonProtoBodyDecoder.kt:10)
        at com.chuckerteam.chucker.internal.support.RequestProcessor$decodePayload$1.invoke(RequestProcessor.kt:71)
        at com.chuckerteam.chucker.internal.support.RequestProcessor$decodePayload$1.invoke(RequestProcessor.kt:13)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:133)
        at com.chuckerteam.chucker.internal.support.RequestProcessor.decodePayload(RequestProcessor.kt:76)
        at com.chuckerteam.chucker.internal.support.RequestProcessor.processPayload(RequestProcessor.kt:59)
        at com.chuckerteam.chucker.internal.support.RequestProcessor.process(RequestProcessor.kt:22)
        at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:66)
        at com.chuckerteam.chucker.sample.InterceptorTypeKt$activeForType$1.intercept(InterceptorType.kt:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

## :bomb: Steps to reproduce
Run the sample and click on `Do HTTP activity`

## :wrench: Expected behavior
No exception in logcat

## :iphone: Tech info
 - Chucker version: [latest version from `develop`](https://github.com/ChuckerTeam/chucker/tree/186a3df44f57846d899c23e3a4f5770b683a7ef9)

**Comment by MiSikora** [comment]
To be honest, that was implemented intentionally to inspect logging. One of the postman requests is not protobuf and `PokemonDecoder` matches based on URL.

I don't mind if you want to change it but just mentioning it FYI.

**Comment by vbuberen** [comment]
Didn't know about it being on purpose. Ok, closing.
