### ISSUE TITLE
Some missing Proguard rules?

### ISSUE THREAD

**Issue by HappyDr0id** [ChuckerTeam/chucker#58]
**Describe the bug**
I get a systematic crash on any build using Proguard when I try to launch a Chucker intent like this for example:
`context.startActivity(Chuck.getLaunchIntent(context, SCREEN_HTTP))`

I don't have any issue if I don't use Proguard, so that's why I guess it may be related to some Proguard rules missing.

Crash logs:
```
E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #2
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.i.b.d$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteException: no such column: tag (code 1 SQLITE_ERROR[1]): , while compiling: SELECT _id, tag, clazz, message, date FROM 'd' ORDER BY date DESC
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1865)
        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1712)
        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1583)
        at e.a.a.f$a.a(DatabaseCompartment.java:641)
        at e.a.a.f.a(DatabaseCompartment.java:437)
        at e.a.a.f.a(DatabaseCompartment.java:53)
        at e.a.a.f$b.a(DatabaseCompartment.java:586)
        at e.a.a.f$b.b(DatabaseCompartment.java:595)
        at com.readystatesoftware.chuck.internal.data.ChuckContentProvider.query(ChuckContentProvider.java:95)
        at android.content.ContentProvider.query(ContentProvider.java:1078)
        at android.content.ContentProvider.query(ContentProvider.java:1170)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:241)
        at android.content.ContentResolver.query(ContentResolver.java:808)
        at android.content.ContentResolver.query(ContentResolver.java:758)
        at androidx.core.content.a.a(ContentResolverCompat.java:81)
        at androidx.i.b.b.h(CursorLoader.java:63)
        at androidx.i.b.b.d(CursorLoader.java:41)
        at androidx.i.b.a.e(AsyncTaskLoader.java:307)
        at androidx.i.b.a$a.a(AsyncTaskLoader.java:60)
        at androidx.i.b.a$a.a(AsyncTaskLoader.java:48)
        at androidx.i.b.d$2.call(ModernAsyncTask.java:141)
```
**To Reproduce**
Enable Proguard and try to launch any Chucker intent.

Thanks a lot in advance for your help! 🙂👋

**Comment by cortinico** [comment]
Hey @HappyDr0id 

Thanks for reporting the bug.
Which version of Chucker are you using?

**Comment by cortinico** [comment]
Also can I ask you to try version `3.0.0-alpha1` and let me know if you still have this issue?

**Comment by HappyDr0id** [comment]
@cortinico thanks for your reactivity! ⚡️
Yep I forgot this info, I'm using the `2.0.4` version, I'll try the alpha version and let you know 👍

**Comment by HappyDr0id** [comment]
@cortinico It works with the `3.0.0-alpha1` version, no issue with Proguard 👏 I'll stay on this version until a stable one will be published, thanks a lot! 🙂

**Comment by cortinico** [comment]
Awesome 👍 Hopefully we'll release a `3.0.0` stable in the near future.
