### ISSUE TITLE
Exception on Android 12 / S

### ISSUE THREAD

**Issue by harry248** [ChuckerTeam/chucker#634]
## :writing_hand: Describe the bug
On Android 12 chucker causes a crash due to a missing intent flag.

## :bomb: Steps to reproduce
Bump compile/target sdk to Android S and try any app using chucker.

## :wrench: Expected behavior
Chucker doesn't crash the app.

## :iphone: Tech info
 - Device: Pixel 4a
 - OS: Android 12 Beta 1
 - Chucker version: 3.4.0

## :page_facing_up: Additional context
java.lang.IllegalArgumentException: de.ocm.app.dev: Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:386)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:470)
        at android.app.PendingIntent.getActivity(PendingIntent.java:456)
        at android.app.PendingIntent.getActivity(PendingIntent.java:420)
        at com.chuckerteam.chucker.internal.support.NotificationHelper$transactionsScreenIntent$2.invoke(SourceFile:47)
        at com.chuckerteam.chucker.internal.support.NotificationHelper$transactionsScreenIntent$2.invoke(SourceFile:19)
        at kotlin.SynchronizedLazyImpl.getValue(SourceFile:74)
        at com.chuckerteam.chucker.internal.support.NotificationHelper.getTransactionsScreenIntent(Unknown Source:2)
        at com.chuckerteam.chucker.internal.support.NotificationHelper.show(SourceFile:101)
        at com.chuckerteam.chucker.api.ChuckerCollector.onRequestSent$com_github_ChuckerTeam_Chucker_library(SourceFile:65)
        at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(SourceFile:111)

**Comment by vbuberen** [comment]
Hey @harry248 
Thanks for reporting this issue. We already have it resolved in our snapshot version: https://github.com/ChuckerTeam/chucker#snapshots-
Please give it a try and let me know if it works fine. 
We will try to cut a new `3.4.1` stable release for Android 12 users in nearest time. Need just to pick non-breaking commits there.

**Comment by vbuberen** [comment]
@harry248 We have just released 3.5.0 with the fix for the issue you reported. Feel free to check it out and let us know how it is going.

**Comment by saramace** [comment]
Hi @vbuberen Just wanted to let you know that I believe one pending intent was missed here: https://github.com/ChuckerTeam/chucker/commit/515b3f0f4ae0fc030d08ca3c98c8a1d3ca7458ee#diff-c5132152b8a29a93267e2854e720cc1c911da352603166ab6b8c8a64caba9059R60 


I noticed it doesn't exist in the latest snapshot version and am trying the snapshot out but having trouble using it in my project due to it being a major release with more changes

**Comment by cortinico** [comment]
> I noticed it doesn't exist in the latest snapshot version and am trying the snapshot out but having trouble using it in my project due to it being a major release with more changes

You're right @saramace, thanks for reporting. The fix is here: #653

**Comment by saramace** [comment]
Thank you so much for the fast fix!

**Comment by saramace** [comment]
Would it be posibile to get 3.5.1 promoted from stage to prod

I noticed the steps just have it go to stage: https://github.com/ChuckerTeam/chucker/runs/3107658830?check_suite_focus=true and its not yet showing in maven central: https://search.maven.org/artifact/com.github.chuckerteam.chucker/library

**Comment by vbuberen** [comment]
Yeah, it looks like we forgot to promote the release.
We just did it, so in a few hours 3.5.1 should be available on Maven central.

**Comment by saramace** [comment]
FYI it doesn't appear that the .aar file was published successfully https://repo.maven.apache.org/maven2/com/github/chuckerteam/chucker/library/3.5.1/
