### ISSUE TITLE
App is getting crashed when resuming from backstack 

### ISSUE THREAD

**Issue by Shubhamsdr3** [ChuckerTeam/chucker#650]
# Steps to reproduce

1. Go to : Chucker home screen by clicking notification tray
2. Then switch to other app
3. Then resume the chucker from recent task
4. App crashed

# Stack trace: 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo
{com.example.myapp/com.chuckerteam.chucker.api.internal.ui.MainActivity}: java.lang.IllegalStateException: You can't access the transaction repository if you don't initialize it!
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3311)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalStateException: You can't access the transaction repository if you don't initialize it!
	at com.chuckerteam.chucker.api.internal.data.repository.RepositoryProvider.transaction(RepositoryProvider.kt:17)
	at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment.getDataSource(TransactionListFragment.java:136)
	at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment.onAttach(TransactionListFragment.java:81)
	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
	at com.chuckerteam.chucker.api.internal.ui.BaseChuckerActivity.onCreate(BaseChuckerActivity.java:34)
	at com.chuckerteam.chucker.api.internal.ui.MainActivity.onCreate(MainActivity.java:41)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
	... 11 more
```

# Android: Tech info
 - Device: Redmi Note-7 Pro
 - OS: Android 10
 - Chucker version: 3.1.0

**Comment by vbuberen** [comment]
Thanks for reporting. 
It looks like you have quite an old version of Chucker.
I would kindly ask you to try same steps on the latest version and let me know if you still have this issue.

**Comment by Shubhamsdr3** [comment]
Sure..will update the version and let you know if encountered with the same. Thanks for suggestion though.

**Comment by vbuberen** [comment]
@Shubhamsdr3 I guess the issue resolved after updating? Can we close this issue?

**Comment by Shubhamsdr3** [comment]
@vbuberen yes , it's working now. We can close this issue. Thank you 😊
