### ISSUE TITLE
Crash when opening from notification after app is closed

### ISSUE THREAD

**Issue by tulang3587** [ChuckerTeam/chucker#68]
**Describe the bug**
When tapping the clear / notification item to clear / open the chucker activity, it crashses instead.

**To Reproduce**
1. Do anything to show the chucker notification
2. Kill the app, chucker notification still persists
3. Tap clear button / the notification itself
4. Crashes

**Smartphone**
 - OS: 8.0.0
 - Lib version: 3.0.0-alpha2

---

`
java.lang.IllegalStateException: You can't access the transaction repository if you don't initialize it!
at com.chuckerteam.chucker.api.internal.data.repository.RepositoryProvider.transaction(RepositoryProvider.kt:16)
at com.chuckerteam.chucker.api.internal.support.ClearTransactionsService.onHandleIntent(ClearTransactionsService.java:25)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:169)
at android.os.HandlerThread.run(HandlerThread.java:65)
`

---

`
java.lang.IllegalStateException: You can't access the transaction repository if you don't initialize it!
at com.chuckerteam.chucker.api.internal.data.repository.RepositoryProvider.transaction(RepositoryProvider.kt:16)
at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment.getDataSource(TransactionListFragment.java:136)
at com.chuckerteam.chucker.api.internal.ui.transaction.TransactionListFragment.onAttach(TransactionListFragment.java:81)
at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1404)
at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
`

**Comment by cortinico** [comment]
Thanks for reporting @tulang3587 
That's actually a bug and #71 sounds like a great fix to me :)
