### ISSUE TITLE
gson proguard issue

### ISSUE THREAD

**Issue by li-lance** [ChuckerTeam/chucker#749]
## :writing_hand: Describe the bug

After the code is obfuscated, click Details to return an error
## :bomb: Steps to reproduce

if isMinifyEnabled = true, we can see this issue.
## :wrench: Expected behavior

add gson proguard
## :iphone: Tech info
 - Device: HUAWEI P30
 - OS:  HarmonyOS(Compatible with API 29)
 - Chucker version: 3.5.2

## :page_facing_up: Additional context

if add gson proguard?
```
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken

##---------------End: proguard configuration for Gson  ----------
```

**Comment by vbuberen** [comment]
Sorry, but it is hard to understand which issue you have. Could you share some more info?

**Comment by li-lance** [comment]
Enable Proguard and try to click api list.
```2021-12-28 10:53:26.894 2207-2207/cn.porsche.app.beta E/CrashReport: #++++++++++Record By Bugly++++++++++#
2021-12-28 10:53:26.894 2207-2207/cn.porsche.app.beta E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2021-12-28 10:53:26.894 2207-2207/cn.porsche.app.beta E/CrashReport: # PKG NAME: cn.porsche.app.beta
2021-12-28 10:53:26.894 2207-2207/cn.porsche.app.beta E/CrashReport: # APP VER: unspecified
2021-12-28 10:53:26.894 2207-2207/cn.porsche.app.beta E/CrashReport: # SDK VER: 3.4.4
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # LAUNCH TIME: 2021-12-28 10:26:23
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # CRASH TYPE: JAVA_CRASH
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # CRASH TIME: 2021-12-28 10:53:26
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # CRASH PROCESS: cn.porsche.app.beta
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # CRASH THREAD: main
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # REPORT ID: ec9af23e-34e9-4875-8861-a6c5d9cff677
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # CRASH DEVICE: ELE-AL00 UNROOT
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # RUNTIME AVAIL RAM:4719222784 ROM:12520189952 SD:12499218432
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # RUNTIME TOTAL RAM:7976189952 ROM:54943285248 SD:54922313728
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: # CRASH STACK: 
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: java.lang.RuntimeException: Missing type parameter.
        at com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(Unknown Source:84)
        at com.google.gson.reflect.TypeToken.<init>(Unknown Source:62)
        at com.chuckerteam.chucker.internal.data.entity.HttpTransaction$c.<init>(Unknown Source:156)
        at com.chuckerteam.chucker.internal.data.entity.HttpTransaction.getParsedRequestHeaders(Unknown Source:156)
        at com.chuckerteam.chucker.internal.data.entity.HttpTransaction.getRequestHeadersString(Unknown Source:170)
        at r9.z$e.invokeSuspend(Unknown Source:227)
        at v10.a.resumeWith(Unknown Source:33)
        at p20.l1.run(Unknown Source:106)
        at w20.e.P(Unknown Source:571)
        at w20.c.c(Unknown Source:750)
        at w20.c.m(Unknown Source:678)
        at w20.c.run(Unknown Source:665)
2021-12-28 10:53:26.895 2207-2207/cn.porsche.app.beta E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#
```

**Comment by MiSikora** [comment]
I'm tempted to call it a Gson bug. They should embed minification rules in their jar. R8 is capable of reading those from `<library-dir>/META-INF/proguard/`.

**Comment by vbuberen** [comment]
Agree with MiSikora here that looks like a Gson bug. 
However, I have a question @li-lance - you use full Chucker library in production app? Or for some reason you need to have R8 turned on for debug builds as well? Asking, since we don't recommend to have full Chucker (not `no-op`) added to production builds for security reasons.

**Comment by koral--** [comment]
There is an open PR for that in GSON repo: https://github.com/google/gson/pull/1929
There is also an official sample with proguard rules: https://github.com/google/gson/tree/master/examples/android-proguard-example

BTW it is subjective if it is a bug in GSON or just lack of the future. R8 is rather Android specific (and new relatively to GSON) while GSON is a java library (Android is a subset of its target). There is no necessity of incorporating 3rd party standards.

**Comment by MiSikora** [comment]
Regardless of whether it is a bug or not, it should be shipped with Gson. It improves the whole ecosystem, which benefits all libraries and apps.

**Comment by cortinico** [comment]
> Regardless of whether it is a bug or not, it should be shipped with Gson

Agree that this is a issue on Gson's end. We could potentially add a note to the README mentioning what are the proguard rules to workaround this problem, but this will create even more confusion. As @vbuberen mentioned, you're not supposed to use Chucker in prod builds and you should not have to deal with proguard at all.

> Or for some reason you need to have R8 turned on for debug builds as well?

Curious to know this as well.

**Comment by li-lance** [comment]
@cortinico @vbuberen  I'm sorry that I didn't write back to you in time. I need to enable R8 to cover part of the test version.For the time being, this is our only log collection channel 😂. i will add proguard in my app.
