### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by alisher-d** [ChuckerTeam/chucker#886]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlin.Pair.component1()' on a null object reference
       at com.chuckerteam.chucker.internal.ui.transaction.TransactionPayloadFragment.onViewCreated$lambda-2(TransactionPayloadFragment.kt:102)
       at com.chuckerteam.chucker.internal.ui.transaction.TransactionPayloadFragment.$r8$lambda$T903xsqZYw_77gb8vnhfSzuuVAk()
       at com.chuckerteam.chucker.internal.ui.transaction.TransactionPayloadFragment$$ExternalSyntheticLambda3.onChanged(:4)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at com.chuckerteam.chucker.internal.support.LiveDataUtilsKt.combineLatest$lambda-2$lambda-0(LiveDataUtils.kt:21)
       at com.chuckerteam.chucker.internal.support.LiveDataUtilsKt.$r8$lambda$mOyt4m3D7rz_Sl6O-_wkqyiVEGQ()
       at com.chuckerteam.chucker.internal.support.LiveDataUtilsKt$$ExternalSyntheticLambda2.onChanged(:8)
       at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
       at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
       at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
       at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by cortinico** [comment]
Can you please fill the issue template?
