### ISSUE TITLE
NoSuchFieldError: No field mDelegate of type Landroid/database/sqlite/SQLiteStatement 

### ISSUE THREAD

**Issue by jd565** [ChuckerTeam/chucker#951]
## :writing_hand: Describe the bug

We are using snapshot release to be able to handle protobuf messages using the new BodyDecoder. After the dependabot update yesterday, all our builds started crashing immediately with:

```
FATAL EXCEPTION: WM.task-1
                                                                                                    Process: com.app.debug, PID: 4976
                                                                                                    java.lang.NoSuchFieldError: No field mDelegate of type Landroid/database/sqlite/SQLiteStatement; in class Landroidx/sqlite/db/framework/FrameworkSQLiteStatement; or its superclasses (declaration of 'androidx.sqlite.db.framework.FrameworkSQLiteStatement' appears in /data/app/com.app.debug-XRSy0k-4wTbrdxDNGhmPJw==/base.apk!classes20.dex)
                                                                                                        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeUpdateDelete(Unknown Source:0)
                                                                                                        at androidx.work.impl.model.WorkProgressDao_Impl.deleteAll(WorkProgressDao_Impl.java:105)
                                                                                                        at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:273)
                                                                                                        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:215)
                                                                                                        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
                                                                                                        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                        at java.lang.Thread.run(Thread.java:764)
```

Downgrading from the snapshot to 3.5.2 (and losing our protobuf support) stop the issue happening. Even though the stacktrace goes through work manager it seems it is because room is running against 2.5.0.

## :bomb: Steps to reproduce

Use snapshot release in app with workmanager and open app

## :wrench: Expected behavior
Doesn't crash

## :page_facing_up: Additional context
Seems like a Room bug/issue to me so have opened https://issuetracker.google.com/issues/265824784 against Room library also.

**Comment by jd565** [comment]
Issue has been resolved - was caused by sentry plugin doing bytecode manipulation of room and breaking everything.
