### ISSUE TITLE
DiskWriteViolation in app initialization

### ISSUE THREAD

**Issue by ivancarras** [ChuckerTeam/chucker#963]
## :writing_hand: Describe the bug

I detected an error in my app using Koin, okHttp and Chucker

```
StrictMode policy violation; ~duration=118 ms: android.os.strictmode.DiskWriteViolation
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1614)
                 	at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:365)
                 	at libcore.io.ForwardingOs.remove(ForwardingOs.java:673)
                 	at android.app.ActivityThread$AndroidOs.remove(ActivityThread.java:7816)
                 	at java.io.UnixFileSystem.delete(UnixFileSystem.java:331)
                 	at java.io.File.delete(File.java:1035)
                 	at com.chuckerteam.chucker.internal.data.room.ChuckerDatabase$Companion.create(ChuckerDatabase.kt:22)
                 	at com.chuckerteam.chucker.internal.data.repository.RepositoryProvider.initialize(RepositoryProvider.kt:34)
                 	at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:32)
                 	at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:23)
                 	at com.chuckerteam.chucker.api.ChuckerInterceptor$Builder.build(ChuckerInterceptor.kt:366)

```
The problems seems to be here: 

```` 
internal abstract class ChuckerDatabase : RoomDatabase()  {
....
        fun create(applicationContext: Context): ChuckerDatabase {
            // We eventually delete the old DB if a previous version of Chuck/Chucker was used.
            applicationContext.getDatabasePath(OLD_DB_NAME).delete()
         }
...
````

## :bomb: Steps to reproduce

1. Stablish strictMode in your app onCreate() as: 
```
    StrictMode.setThreadPolicy(
      StrictMode.ThreadPolicy.Builder()
        .detectDiskWrites()
        .penaltyLog()
        .penaltyFlashScreen()
        .build()
    )
```
2. Create a ChuckerInterceptor in the koin definitions: 
```
 single { ChuckerInterceptor.Builder(androidContext()).build() }
```

3. Init your app and take a look at the logs 
```
16:54:55.637  D  StrictMode policy violation; ~duration=118 ms: android.os.strictmode.DiskWriteViolation
                 	at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1614)
                 	at libcore.io.BlockGuardOs.remove(BlockGuardOs.java:365)
                 	at libcore.io.ForwardingOs.remove(ForwardingOs.java:673)
                 	at android.app.ActivityThread$AndroidOs.remove(ActivityThread.java:7816)
                 	at java.io.UnixFileSystem.delete(UnixFileSystem.java:331)
                 	at java.io.File.delete(File.java:1035)
                 	at com.chuckerteam.chucker.internal.data.room.ChuckerDatabase$Companion.create(ChuckerDatabase.kt:22)
                 	at com.chuckerteam.chucker.internal.data.repository.RepositoryProvider.initialize(RepositoryProvider.kt:34)
                 	at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:32)
                 	at com.chuckerteam.chucker.api.ChuckerCollector.<init>(ChuckerCollector.kt:23)
                 	at com.chuckerteam.chucker.api.ChuckerInterceptor$Builder.build(ChuckerInterceptor.kt:366)
```

## :wrench: Expected behavior

Not blocking the main thread in the app initialization

## :iphone: Tech info
 - Device: Pixel 4a
 - OS: Android 13
 - Chucker version: 3.5.2

**Comment by vbuberen** [comment]
Try the latest SNAPSHOT version as we should have this bug fixed there: https://github.com/ChuckerTeam/chucker/blob/develop/CHANGELOG.md#fixed

**Comment by ivancarras** [comment]
@vbuberen We are actually using the last library which is 3.5.2 right?

**Comment by ivancarras** [comment]
@vbuberen Perfect I'll check it out ,thanks

**Comment by cortinico** [comment]
> @vbuberen Perfect I'll check it out ,thanks

Please let us know if this resolves your issue @ivancarras 👍

**Comment by ivancarras** [comment]
Sorry for the delay, in version `4.0.0-SNAPSHOT` this issue is solved, do you know when you are going to release this version? thanks @cortinico @vbuberen

**Comment by cortinico** [comment]
> Sorry for the delay, in version `4.0.0-SNAPSHOT` this issue is solved, do you know when are you going to release this version? thanks @cortinico @vbuberen

Sorry we don't have an ETA at the moment
