### ISSUE TITLE
I got a crash

### ISSUE THREAD

**Issue by GitHubKlod** [ChuckerTeam/chucker#969]
## :writing_hand: Describe the bug
Jump TransactionActivity Crash

## :bomb: Steps to reproduce
Click TransactionListFragment Adapter Item

## :iphone: Tech info
 - Device: simulator
 - OS: 9
 - Chucker version: 3.5.2

## :page_facing_up: Additional context
FATAL EXCEPTION: main
                                                 Process: com.zjbbsm.uubaoku, PID: 19213
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zjbbsm.uubaoku/com.chuckerteam.chucker.internal.ui.transaction.TransactionActivity}: android.view.InflateException: Binary XML file line #42: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior
                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2954)
                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3089)
                                                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1819)
                                                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                 	at android.os.Looper.loop(Looper.java:193)
                                                 	at android.app.ActivityThread.main(ActivityThread.java:6737)
                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
                                                 Caused by: android.view.InflateException: Binary XML file line #42: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior
                                                 Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass android.support.design.widget.AppBarLayout$ScrollingViewBehavior
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:649)
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896)
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740)
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112)
                                                 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                 	at com.chuckerteam.chucker.databinding.ChuckerActivityTransactionBinding.inflate(ChuckerActivityTransactionBinding.java:60)
                                                 	at com.chuckerteam.chucker.databinding.ChuckerActivityTransactionBinding.inflate(ChuckerActivityTransactionBinding.java:54)
                                                 	at com.chuckerteam.chucker.internal.ui.transaction.TransactionActivity.onCreate(TransactionActivity.kt:33)
                                                 	at android.app.Activity.performCreate(Activity.java:7144)
                                                 	at android.app.Activity.performCreate(Activity.java:7135)
                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2934)
                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3089)
                                                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1819)
                                                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                 	at android.os.Looper.loop(Looper.java:193)
                                                 	at android.app.ActivityThread.main(ActivityThread.java:6737)
                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
                                                 Caused by: java.lang.ClassNotFoundException: android.support.design.widget.AppBarLayout$ScrollingViewBehavior
                                                 	at java.lang.Class.classForName(Native Method)
                                                 	at java.lang.Class.forName(Class.java:453)
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:642)
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2896) 
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1740) 
                                                 	at androidx.coordinatorlayout.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:112) 
                                                 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865) 
                                                 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                 	at com.chuckerteam.chucker.databinding.ChuckerActivityTransactionBinding.inflate(ChuckerActivityTransactionBinding.java:60) 
                                                 	at com.chuckerteam.chucker.databinding.ChuckerActivityTransactionBinding.inflate(ChuckerActivityTransactionBinding.java:54) 
                                                 	at com.chuckerteam.chucker.internal.ui.transaction.TransactionActivity.onCreate(TransactionActivity.kt:33) 
                                                 	at android.app.Activity.performCreate(Activity.java:7144) 
                                                 	at android.app.Activity.performCreate(Activity.java:7135) 
                                                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
                                                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2934) 
                                                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3089) 
                                                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                                                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1819) 
                                                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                 	at android.os.Looper.loop(Looper.java:193) 
                                                 	at android.app.ActivityThread.main(ActivityThread.java:6737) 
                                                 	at java.lang.reflect.Method.invoke(Native Method) 
                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860) 
2023-02-22 19:53:36.305 com.zjbbsm.uubaoku    E  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.AppBarLayout$ScrollingViewBehavior" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.zjbbsm.uubaoku-g31kgnZoX9v9VfQmtreGxQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.zjbbsm.uubaoku-g31kgnZoX9v9VfQmtreGxQ==/lib/arm, /data/app/com.zjbbsm.uubaoku-g31kgnZoX9v9VfQmtreGxQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
                                                 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by GitHubKlod** [comment]
I fix this
use
 com.google.android.material:material:1.1.0
and use it like this:
  <string name="appbar_scrolling_view_behavior" tools:ignore="MissingTranslation">com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior</string>
in my app strings.xml
